version: '3.8'

services:
  api:
    image: ghcr.io/penghu6/imagica2.api:develop
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /data/050819521/file/imagica2/bucket:/bucket
      - /data/050819521/file/imagica2/storage:/storage
      - /data/050819521/imagica2Config/.env:/.env
    working_dir: /app