version: '3.8'

services:
  api:
    image: registry.cn-hangzhou.aliyuncs.com/seolove/imagica2:develop
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /data/050819521/file/imagica2/bucket:/bucket
      - /data/050819521/file/imagica2/storage:/storage
      - /data/050819521/imagica2Config/.env:/.env
    working_dir: /app
    user: "1000:1000"
    command: >
      sh -c "
        mkdir -p /bucket/temp &&
        chown -R node:node /bucket &&
        chown -R node:node /storage &&
        ls -la /app &&
        pwd &&
        node -v &&
        npm list &&
        node bin/www
      "