version: '3.8'

services:
  api:
    image: registry.cn-hangzhou.aliyuncs.com/seolove/imagica2:develop
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /data/050819521/file/imagica2/bucket:/bucket
      - /data/050819521/file/imagica2/storage:/storage
      - /data/050819521/imagica2Config/.env:/.env
    working_dir: /app